project:
  type: website
  output-dir: docs

website:
  title: "howeini"
  navbar:
    left:
      - index.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

