---
title: "Code-Alongs & Challenges"
---

<hr>

On [Github](https://github.com/howeini/NM2207), you can find all my Code-Along documents & Challenges from Weeks 1-9 as well as my diary entries for the Final Project. I've elaborated on my learning points for each week below.

## Week 1

-   Learnt how to create and navigate a R Markdown Document

## Week 2

-   Introduced to Exploratory Data Analysis, **ggplot** and **Shiny**

## Week 3

-   Introduced to the different type of variables in a data set
-   Learnt to create vectors and lists for the different variable types, and how to access the elements
-   Implicit and explicit coercion

## Week 4

-   Learnt about Data Wrangling
-   This is arguably one of the more important lessons for our final project

## Week 5

-   Learnt how to write Functions
-   Local and global variables

## Week 6

-   For loops and While loops

## Week 7

-   Visualising data using **ggplot2**

## Week 8

-   Exploring **Shiny**

## Week 9

-   Introduced to different methods of tidying data, scraping data from the Web and collecting data using APIs
-   Final Project Proposal

## Week 10
- Exploring data set to see how I can answer the data story question
- Exporing **plotly** to make ggplot interactive
- Embedding Shiny into Quarto
- Plotting different charts based on inputs in Shiny

## Week 11
- Crafted the flow of my data story
- Input placeholders for text and visualisations
- Explored how to stack graphs and make carousels
- Computing a correlation matrix
- Exploring heat maps and bubble maps
- Exploring **Random Forest Model**

## Week 12
- Completed the structure for Shiny App #1: [Attribute Distribution](https://howeini.shinyapps.io/AttributeDist/)
- Completed the structure for Shiny App #2: [World Map Visualisation](https://howeini.shinyapps.io/WorldMap/)

## Week 13
- Completed Final Project
